"""empty message

Revision ID: 447d77050a23
Revises: 7948666e4ff5
Create Date: 2021-10-12 23:29:37.960177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447d77050a23'
down_revision = '7948666e4ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sec_users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('sec_users', 'verification',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sec_users', 'verification',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sec_users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
